# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
 name: 'azureagent'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'basicPython-ACR'
        repository: 'basicPython'
        command: 'build'
        Dockerfile: '/Dockerfile'
        
- stage: Push
  displayName: Push image
  jobs:
  - job: Push
    displayName: Push
    steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'basicPython-ACR'
            repository: 'basicPython'
            command: 'push'